#!/bin/bash
set -e

profile_file=$1
profile=$2
@CHECK_PROFILE@
current=$(cat $profile_file)
if [ $profile == $current ]; then
   echo "$profile is already the current profile"
   exit 1
fi
read -n 1 -r  -p "Select bf_router profile \"$profile\" and reload the data-plane processes? [y/n] "
if [[ $REPLY =~ ^[Yy]$ ]]; then
   echo $profile >$profile_file
   exit 0
fi
echo -e "\nAborting, current profile remains active"
exit 1
