#!/bin/bash
set -e

profile_file=$1
profile=$2
@CHECK_PROFILE@
if [ -e $profile_file ]; then
    current=$(cat $profile_file)
else
    current="<none>"
fi
if [ "$current" != "$profile" ]; then
    echo "Changing P4 profile from $current to $profile, restarting data-plane processes"
fi
echo $profile >$profile_file
exit 0
