#!/bin/bash
set -e

file=/etc/freertr/switch-to-generation
if [ $# -eq 0 ]; then
    if [ -e $file ]; then
	echo "Next reload will activate generation $(cat $file)"
    else
	echo "No switch of generation is currently scheduled"
    fi
    echo "Please supply the RARE profile generation to use at the next reload"
    echo "Use \"tna-list-installed\" to see all currently installed generations"
    exit 0
fi
gen=$1
PROFILE=@NIX_PROFILE@
if ! [ -h $PROFILE-$gen-link ]; then
    echo "$gen is not a valid generation"
    echo "Use \"tna-list-installed\" to see all currently installed generations"
    exit 0
fi
echo $gen >$file
echo "Setting RARE profile generation to $gen"
echo "Use \"reload warm\" to activate"
