#!/bin/bash
set -e

file=/etc/freertr/switch-to-generation
if [ $# -eq 0 ]; then
    echo "Please supply the RARE profile generation number you want to switch to"
    echo "Use \"tna-list-installed\" to see all currently installed generations"
    exit 1
fi
gen=$1
PROFILE=@NIX_PROFILE@
if ! [ -h $PROFILE-$gen-link ]; then
    echo "$gen is not a valid generation"
    echo "Use \"tna-list-installed\" to see all currently installed generations"
    exit 1
fi
read -n 1 -r  -p "Set RARE profile generation to $gen and restart freerouter? [y/n] "
if [[ $REPLY =~ ^[Yy]$ ]]; then
    echo $gen >$file
   exit 0
fi
echo -e "\nAborting, current profile remains active"
exit 1
